language: ruby
rvm:
  - 2.1.1
env:
  global:
    - RAILS=4.0.4
    - DB=postgresql
    - APP_SECRET_KEY_BASE='travis-secret-key'
branches:
  only:
    - master
before_script:
  - psql -c 'create database app_test;' -U postgres
  - 'bundle exec rake db:migrate'
